name: history_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.12
  firebase_database: ^7.1.2
  firebase_analytics: ^8.2.0
  connectivity: ^3.0.6
  youtube_player_flutter: ^8.0.0
  audioplayers: ^0.20.1
  provider: ^5.0.0
  string_validator: ^0.3.0
  shared_preferences: ^2.0.11

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/Logo/custom_Logo_crop.png
    - assets/images/Logo/logo.png
    - assets/images/contentBackground.png
    - assets/images/Map/continent.jpg
    - assets/images/Map/map.jpg

    #QUIZ 1
    - assets/images/quiz1/mughalrule.jpg
    - assets/images/quiz1/shalimargardens.jpg
    - assets/images/quiz1/twonations.jpg
    - assets/images/quiz1/uni.jpg
    - assets/images/quiz1/war.jpg
    #QUIZ 2
    - assets/images/quiz2/continets.jpeg
    - assets/images/quiz2/Cpakistan.png
    - assets/images/quiz2/mappakistan.jpeg
    - assets/images/quiz2/Neighcountry.gif
    - assets/images/quiz2/oceans.jpeg
    #QUIZ 3
    - assets/images/quiz3/capitalcity.jpeg
    - assets/images/quiz3/fullname.jpg
    - assets/images/quiz3/independenceday.jpeg
    - assets/images/quiz3/languages.jpeg
    - assets/images/quiz3/religion.jpeg
    #QUIZ 4
    - assets/images/quiz4/garden.jpg
    - assets/images/quiz4/khybar.jpeg
    - assets/images/quiz4/ludo.jpeg
    - assets/images/quiz4/Shahabdul.jpeg
    - assets/images/quiz4/sibi.jpeg
    #QUIZ 5
    - assets/images/quiz5/childlabour.jpeg
    - assets/images/quiz5/constitution.jpeg
    - assets/images/quiz5/humanrights.jpeg
    - assets/images/quiz5/UN.jpeg
    - assets/images/quiz5/vote.png
    #Farwa's Work
    - assets/images/continent.jpg
    - assets/images/map.jpg
    - assets/images/heroes/fatimajinnah.jpg
    - assets/images/heroes/Jinnah.jpg
    - assets/images/heroes/sir.jpg
    - assets/images/heroes/allama.jpg
    - assets/images/heroes/liaquath.jpg
    - assets/images/heroes/molana.jpg
    - assets/images/heroes/edhi.jpeg
    #Faaiz Work
    #culture audio
    - assets/audio/Sindhi_cultural_Algoza_saaz.mp3
    - assets/audio/pakistani_pashto_traditional_music.mp3
    - assets/audio/Folk_music_of_Gilgit Baltistan.mp3
    - assets/audio/Fok_song_of_Kashmir.mp3
    - assets/audio/Energatic_Bhangra_Beat.mp3
    - assets/audio/Beautiful_Balochi_folk_song.mp3
    #culture dress
    - assets/images/dress/1.jpg
    - assets/images/dress/balti.png
    - assets/images/dress/kashmiri.PNG
    - assets/images/dress/pashto.PNG
    - assets/images/dress/sindhi.PNG
    - assets/images/dress/punjabi.PNG

    #Addons
    - assets/images/new/Ibrahim Lodhi.jpeg
    - assets/images/new/akbar.jpeg
    - assets/images/new/Bahadur shah zafar.jpeg
    - assets/images/new/The divine religion.jpeg
    - assets/images/new/shah-jahan.jpeg
    - assets/images/new/Babur.jpeg
    - assets/images/new/war of indepence.webp
    - assets/images/new/British won 1857.jpeg
    - assets/images/new/camps for migrants.jpeg
    - assets/images/new/people killed.jpeg
    - assets/images/new/the great migration.jpeg
    - assets/images/new/trains.jpeg
    - assets/images/new/women during migration.jpeg
    - assets/images/new/a_king_or_queen.jpeg
    - assets/images/new/bangladesh.png
    - assets/images/new/government.jpg
    - assets/images/new/Pakistan.jpeg
    - assets/images/new/powerpeople.png
    - assets/images/new/rights of people.png
    - assets/images/new/screenshot.png
    - assets/images/new/Sovereignty2.jpeg
    - assets/images/new/voting.jpg
    - assets/images/new/reformer.jpg
    - assets/images/new/Aligarh College.jpeg
    - assets/images/new/Aligarh Movement.png
    - assets/images/new/Allam Iqbal poetry.png
    - assets/images/new/Ambassador of Hindu Muslim Unity.png
    - assets/images/new/communication skills.jpeg
    - assets/images/new/Fatima Jinnah.jpeg
    - assets/images/new/Quaid e azam.jpeg
    - assets/images/new/Sir-Syed-Ahmad-Khan.jpeg
    - assets/images/new/The poet of the East.jpeg
    - assets/images/new/two nations theory.jpeg
    - assets/images/new/Urdu Hindi Controversy.png
    - assets/images/new/women-political-participation.jpeg
    - assets/images/new/Aligarh College.jpeg
    - assets/images/new/Babur copy.jpeg
    - assets/images/new/British Eduation.png
    - assets/images/new/Indian National congress.jpeg
    - assets/images/new/Muslim League.png
    - assets/images/new/Screenshot 2021-10-13 at 8.28.01 AM.png
    - assets/images/new/Sir syed.jpeg
    - assets/images/new/two nations theoy copy.jpeg
    - assets/images/new/war of independence.jpeg
    - assets/images/new/Pakistan Resolution.jpeg
    - assets/images/new/cyrus_cylinder copy.jpeg
    - assets/images/new/war.jpg
    - assets/images/new/alliance2.png
    - assets/images/new/allied-powers.jpeg
    - assets/images/new/central powers.png
    - assets/images/new/CYRUS copy.png
    - assets/images/new/Germany.jpeg
    - assets/images/new/King John.jpeg
    - assets/images/new/machine guns copy.jpeg
    - assets/images/new/magna carta.jpg
    - assets/images/new/people died .jpeg
    - assets/images/new/Right to fair Trial.jpeg
    - assets/images/new/treatyof versailles.jpg
    - assets/images/new/socrates-9488126-1-402 copy.jpeg
    - assets/images/new/UDHR.jpeg
    - assets/images/new/xenophon copy.jpeg
    - assets/images/new/hitler.jpg


  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,      # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: Regular
        fonts:
            - asset: assets/fonts/bolt-regular.ttf
      - family: Bold
        fonts:
            - asset: assets/fonts/bolt-semibold.ttf

      - family: Quote
        fonts:
          - asset: assets/fonts/Courgette-Regular.ttf

      - family: StyleQuote
        fonts:
          - asset: assets/fonts/DancingScript-Bold.ttf


  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
